name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello there"
      - name: Bye
        run: echo "bye there"
      - name: Printer
        run: |
            echo "It's good to have you here"
            echo "I hope you learn a lot"
            echo "Let me know when you're done"
